-- =====================================================
-- 기억을 잇다
-- SUPABASE DATABASE
-- =====================================================


-- 기존 테이블 삭제
drop table if exists public.memories;


-- =====================================================
-- 기억 테이블
-- =====================================================

create table public.memories (

  id bigint generated by default as identity
    primary key,

  memory text not null,

  emotion text not null,

  feeling text not null,

  reflection text not null,

  category text not null,

  created_at timestamptz
    not null
    default now()

);


-- =====================================================
-- RLS
-- =====================================================

alter table public.memories
enable row level security;


-- =====================================================
-- 누구나 기억을 볼 수 있음
-- =====================================================

create policy
"Anyone can read memories"

on public.memories

for select

to anon

using (
  true
);


-- =====================================================
-- 누구나 기억을 남길 수 있음
-- =====================================================

create policy
"Anyone can insert memories"

on public.memories

for insert

to anon

with check (
  true
);
